"""media assets and plan status

Revision ID: ef1229e23ee8
Revises: 27327f38f6e8
Create Date: 2026-09-06 00:34:02.091167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ef1229e23ee8'
down_revision: Union[str, Sequence[str], None] = '27327f38f6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=True),
    sa.Column('source_asset_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('analysis_status', sa.String(length=12), server_default='pending', nullable=False),
    sa.Column('stage_summary', sa.Text(), nullable=True),
    sa.Column('equipment_summary', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_entry_id'), 'media_assets', ['entry_id'], unique=False)
    op.create_index(op.f('ix_media_assets_project_id'), 'media_assets', ['project_id'], unique=False)
    op.add_column('projects', sa.Column('plan_status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'plan_status')
    op.drop_index(op.f('ix_media_assets_project_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_entry_id'), table_name='media_assets')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
